name: dart_app
description: University management system with real-time updates
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Server dependencies
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_web_socket: ^1.0.4

  # Database
  postgres: ^3.0.0

  # Environment variables
  dotenv: ^4.0.1

  # JSON serialization
  json_annotation: ^4.8.0

  # Web
  web: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^3.0.0
